singlearm:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    variable_impedance_controller:
      type: singlearm_controller/VariableImpedanceController
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
        - ft_sensor_joint

      root_link: elfin_base_link
      tip_link: elfin_tool_ball
      
      joint1:
        tdc: {mbar: 0.02, r: 10.0, a: 50.0, w: 0.004, p: 45.0, d: 3.0}
      joint2: 
        tdc: {mbar: 0.02, r: 10.0, a: 50.0, w: 0.004, p: 45.0, d: 3.0}
      joint3: 
        tdc: {mbar: 0.01, r: 10.0, a: 50.0, w: 0.004, p: 45.0, d: 3.0}
      joint4: 
        tdc: {mbar: 0.004, r: 10.0, a: 50.0, w: 0.004, p: 45.0, d: 3.0}
      joint5: 
        tdc: {mbar: 0.003, r: 10.0, a: 50.0, w: 0.004, p: 45.0, d: 3.0}
      joint6: 
        tdc: {mbar: 0.001, r: 10.0, a: 50.0, w: 0.004, p: 45.0, d: 3.0}
      joint7:
        tdc: {mbar: 0.0, r: 0.0, a: 0.0, w: 0.0, p: 0.0, d: 0.0}

      aic: {fd: 20.0, m: 5.0, b: 300.0}

      # mode = 0 -> No Filter, Fd(fixed)
      # mode = 1 -> Filter, Fd(fixed)
      # mode = 2 -> Filter, Fd(sin)

      mode: 1
